### ISSUE TITLE
CDN version of dataTables.bootstrap.css differs from github version of dataTables.bootstrap.css

### ISSUE THREAD

**Issue by cookch10** [DataTables/Plugins#164]
http://www.datatables.net/manual/styling/bootstrap has CDN references for dataTables.bootstrap.css and dataTables.bootstrap.js.

The CDN version of dataTables.bootstrap.css on that page points here:  http://cdn.datatables.net/plug-ins/f2c75b7247b/integration/bootstrap/3/dataTables.bootstrap.css

The CDN CSS file is slightly different from the one on github:  https://raw.githubusercontent.com/DataTables/Plugins/master/integration/bootstrap/3/dataTables.bootstrap.css

The JS files are the same.  Is this expected?  Would it be possible to include some sort of time-stamp or version information in these assets to make upgrading easier and also aid in determining which assets may be out of date?

**Comment by DataTables** [comment]
Yes, quite expected. The plug-ins are released now and then - https://github.com/DataTables/Plugins/releases . I should perhaps update the DataTables CDN to use the version number rather than the commit hash now that is it available. Might make the upgrading you mention easier as well. I'll leave this bug open until I can do that.

**Comment by cookch10** [comment]
Thanks!

**Comment by DataTables** [comment]
Finally fixes now with the 1.10.6 release :-)

**Comment by cookch10** [comment]
(thumbsup)
