### ISSUE TITLE
Bootstrap integration - Bootlint validation warnings

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [DataTables/Plugins#194]
Hello!

The following bootstrap datatable got bootlint warnings:

```
$("#example1").dataTable({
    "bLengthChange": false,
    "bFilter": false,
    "bInfo": false
});
```

Since there isn't a top filter and a bottom info in this table, the final html got 3 empty divs, which won't pass bootlint validation.

Here is the html result for that datatable configuration:

![table](https://cloud.githubusercontent.com/assets/12160864/7847192/70d8c4a0-0498-11e5-9e55-3f107586372f.png)

And here are the bootlint validation warnings:

![bootlint](https://cloud.githubusercontent.com/assets/12160864/7847201/865181dc-0498-11e5-8962-cba86772a718.png)

Is this a "bug" in bootstrap integration, or some wrong configuration in my datatable?

Thanks.

**Comment by DataTables** [comment]
This is a warning rather than an error if I understand correctly. To paraphrase the warning message, it isn't necessary, but it is acceptable to have the empty div elements.

You could if you wish specify your own `dom` option for DataTables rather than using the Bootstrap integration default, but I don't consider this to be a bug.

**Comment by rafael-renan-pacheco** [comment]
Yes, this is just a warning, that's why I wrote "bug".

I'll try to use DataTable without this integration, thanks :+1:
