### ISSUE TITLE
add package.json

### ISSUE THREAD

**Issue by maruilian11** [DataTables/Plugins#224]
would you please consider adding package.json so that we can add your lib on https://cdnjs.com.
thank you very much!
https://github.com/cdnjs/cdnjs/issues/5234

**Comment by DataTables** [comment]
Yes! I'm working on various updates related to this for the core DataTables packages. It will be a little bit longer before this repo is updated to contain distribution files, but not too long I hope!

**Comment by maruilian11** [comment]
it's ok. take your time :)

**Comment by jankrueger** [comment]
Hi, could you give an estimation when you can release a version with npm support? Is there anything that can be done to assist you? There already seems to be an open PR that adds that enhancement. Thanks :)

**Comment by DataTables** [comment]
npm support for this repo is potentially fairly involved and might in fact require splitting every file out into its own repo so that they can be included as required. I don't really want to do that!

Certainly all of the JS files need to be updated to support CommonJS and AMD loaders.

Full npm support for this repo is something I hope to achieve, but there are other things on my todo list first.

**Comment by jankrueger** [comment]
Ok, thanks for your answer :)

**Comment by arderyp** [comment]
+1

**Comment by arderyp** [comment]
@DataTables I think you can close this now thanks to https://github.com/DataTables/Plugins/issues/81

Thanks again!
