### ISSUE TITLE
SearchPane Feature Request: Optionally Inherit Column or Table-Level Sorting

### ISSUE THREAD

**Issue by ChrisDrozdowski** [DataTables/Plugins#373]
For SearchPanes please consider adding support for optionally add support for inheriting sorting from the relevant column or table-level sorting.

**Comment by DataTables** [comment]
Thanks! Yup - it makes perfect sense and it already on the [list of enhancements requested](https://datatables.net/forums/discussion/46119/searchpane-feedback#latest). Its going to require a bit of work in DataTables to make that possible since the sort isn't externally exposed yet, but it should come.
