### ISSUE TITLE
SearchPane doesn't filter rendered data

### ISSUE THREAD

**Issue by tonynamy** [DataTables/Plugins#452]
Hello, I am Korean student developing student management console for my school.

When I am using datatables, I defined render function in columns.

But SearchPane doesn't seem to filter data with render value but pure data.

As you can see in my Fiddle, I give numeric data to columns and render them to visualized HTML code. 

Fiddle : https://jsfiddle.net/usbzL68q/1/

How can I make search pane filter with not data, but actually visible content? (Or, how can I make SearchPane use render function which I defined?)

==> I want to make the contents inside 'status' to html code, not numbers. In my fiddle, I want to show VXVX (html element) as in table, not a number 8.

Thanks.

**Comment by SandyDatatables** [comment]
Hi tonynamy,

I am currently working towards making SearchPanes a full feature for DataTables. The new and improved SearchPanes automatically copes with rendering data. I.e. if you are using rendering within a column in your DataTable then SearchPanes will automatically adopt this rendering for the pane.

We are hoping to release SearchPanes properly in the coming weeks but in the mean time you can find all of the code in this repository - https://github.com/DataTables/SearchPanes . Feel free to have a look at the source code. It would be worth looking in particular at https://github.com/DataTables/SearchPanes/blob/master/src/searchPane.ts around line 994.

Here we are extracting both the original data and the rendered data from the table, We then proceed to populate the pane using this data, displaying the rendered data to the user while sorting and searching on the original data.

I've taken your js fiddle and adapted it slightly so that it is now running on the new Feature - https://jsfiddle.net/9Lhpmu38/5/

Please feel free to play around with this if you so desire. Please also note that this feature is not fully supported yet and documentation etc. will follow shortly.

Hope that this helps,

Sandy

**Comment by SandyDatatables** [comment]
Hi again tonynamy,

Just following up on this and wondered how you got on?

Thanks,

Sandy

**Comment by tonynamy** [comment]
Hi Sandy,

Thanks for your help.

I checked your fiddle, but it seems that the design of new feature is not stable. 

Some icons are breaking in some browsers, and also the fluid style not applying. 

Because of the reasons above, I couldn't apply your code in my service.

If you don't mind, would you check the problems and give me some feedback?

Besides, your fiddle not working well when I checked again now.

Thanks for your help again,

tonynamy
