### ISSUE TITLE
SearchPanes and custom render function

### ISSUE THREAD

**Issue by ikkez** [DataTables/Plugins#484]
Is there a way to define a different render function for the searchPanes column?
Because my render function I already have (type = display) for the datatable returns some html, which is not very practical that way in the filter search panes. Thank you.

**Comment by SandyDatatables** [comment]
Hi @ikkez ,

Yes that is possible by making use of the [searchPanes.dtOpts](https://datatables.net/reference/option/searchPanes.dtOpts) or [columns.searchPanes.dtOpts](https://datatables.net/reference/option/columns.searchPanes.dtOpts) properties. They allow you to set the DataTables properties for the tables that SearchPanes uses. Take a look at [this example](https://datatables.net/extensions/searchpanes/examples/customisation/dtOpts.html).

We would much prefer that you use the [DataTables Forum](https://datatables.net/forums/) to ask support questions. I'm going to close this issue. If you have any further questions, on this topic or otherwise, please direct them to the forum.

Thanks,
Sandy
