### ISSUE TITLE
flatten is deprecated in favor of utility frameworks such as lodash

### ISSUE THREAD

**Issue by arderyp** [DataTables/Plugins#564]
Yarn is giving me the following warning 

```
warning datatables.net-plugins > prettier-plugin-x > x-formatter > @prettier-x/formatter-2021-01 > postcss-selector-parser > flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
warning datatables.net-plugins > prettier-plugin-x > x-formatter > @prettier-x/formatter-2021-01 > postcss-values-parser > flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
```

**Comment by AllanJard** [comment]
Thank you.

That is coming from the dev dependency `prettier-plugin-x`. Previously I'd had that as a regular dependency, rather than a dev one, but that was fixed [in this commit](https://github.com/DataTables/Plugins/commit/41681850e2f870187cab1b106ce02eb8ceb83d6d). There hasn't been a release with that yet - there will be soon, which will mean the warning is no longer displayed.

**Comment by arderyp** [comment]
Thanks @AllanJard !
