### ISSUE TITLE
utf-8 encoding issue introduced recently

### ISSUE THREAD

**Issue by violuke** [DataTables/Plugins#568]
Our post-processing of this package has been broken in a recent update.

I *think* this diff shows the issue: https://github.com/DataTables/Plugins/commit/e405113d46435227a09b7f4270abeaa9d36c7786#diff-abc77132b3d56a7c70103d292bc76bf71972dcd6b24a861e3c526df122c23692

<img width="1367" alt="Screenshot 2023-07-29 at 11 44 53" src="https://github.com/DataTables/Plugins/assets/6420347/f435cd6d-fa19-470d-a04d-c8cd38991731">

**Comment by AllanJard** [comment]
Thank you! I've [fixed it with this commit](https://github.com/DataTables/Plugins/commit/9047d05de714e8a98a558a3b92462c6097c34c9c).

I don't understand the fix I'll be perfectly honest. My terminal seems to need simple `echo` before outputting the file, otherwise it writes rubbish as has been seen. However, with the addition of `echo -n " "` before the output in the wrapper script, it works!

**Comment by violuke** [comment]
Thank you, much appreciated :+1:
